workflows:

  # Build APK development and send to gmail
  build-android-apk-dev:
    name: Build android .apk dev
    scripts:
      - name: Install npm dependencies # Name of the section
        script: npm install --legacy-peer-deps
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build APK # Name of the section
        script: cd android &&
          ./gradlew clean &&
          ./gradlew assembleDevRelease

    artifacts:
      - android/app/build/outputs/apk/dev/release/*.apk
    publishing:
      email:
        recipients:
          - dekapro9x@gmail.com
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails

  # Build APK production and send to gmail
  build-android-apk-prod:
    name: Build android .apk prod
    scripts:
      - name: Install npm dependencies # Name of the section
        script: npm install --legacy-peer-deps
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build APK # Name of the section
        script: cd android &&
          ./gradlew clean &&
          ./gradlew assembleProdRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dekapro9x@gmail.com
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails

  build-android-bundle:
    name: Build android .aab
    scripts:
      - name: Install npm dependencies # Name of the section
        script: npm install --legacy-peer-deps
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build file bundle # Name of the section
        script: cd android &&
          ./gradlew clean &&
          ./gradlew bundleProdRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - dekapro9x@gmail.com
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails